name: fbla_member_app
description: Starter FBLA member app (Flutter)
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

# (add assets if you include images)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true